version: '3.4'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/sh -c 'composer install && composer exec -- phpunit'"
    depends_on:
      - tidb
    entrypoint: []
    volumes:
      - .:/project:delegated
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
