version: "3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    entrypoint: ./wait-for-it.sh tidb:4000 -t 600 --
    command: /bin/sh -c "composer install && vendor/bin/phpunit"
    volumes:
      - .:/project:delegated
    depends_on:
      - tidb
  tidb:
    build:
      context: .
      dockerfile: Dockerfile.tidb
    image: ubuntu:latest
    command: /bin/sh -c "/root/.tiup/bin/tiup playground --db.host=0.0.0.0"
    environment:
      TZ: "Asia/Tokyo"
